project:
  type: website

website:
  title: "Data Séance"
  navbar:
    left:
      - text: About
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/bradisbrad
      - icon: linkedin
        href: https://www.linkedin.com/in/jhill101/
format:
  html:
    theme: 
      light: [lux, theme.scss]
      dark: [lux, dark_theme.scss]
    code-tools: true
    highlight-style: a11y

editor: visual

